# SPRING CORE
spring:
  application:
    name: kotlin with spring-boot 1.5.10
# OUTPUT
  output:
    ansi:
      enabled: detect
# PROFILES
  profiles:
    active: dev
# DATASOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false
    username: demo_user
    password: demo_pass
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      default-auto-commit: false
      default-read-only: false
      validation-query: select 1
      validation-query-timeout: 3
      time-between-eviction-runs-millis: 3600000
      test-on-borrow: true
      test-while-idle: true
      test-on-connect: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      max-active: 4
      initial-size: 4
      max-idle: 4
      min-idle: 0
# JPA
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
  jackson:
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
      write_durations_as_timestamps: true

# EMBEDDED SERVER CONFIGURATION
server:
  port: 9000
  context-path: /app

logging:
  file: demo-kotlin-spring.log
  level:
    root: INFO
    org.springframework: INFO
#    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
#    org.springframework.transaction: TRACE
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.transaction: DEBUG
#    org.hibernate.jpa.internal: DEBUG
#    org.hibernate.event.internal: DEBUG
#    org.hibernate.engine.transaction.internal: DEBUG
#    org.hibernate.internal.util: DEBUG
    com.example.demokotlin: DEBUG
